default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  joint_1:
    has_velocity_limits: false
    has_acceleration_limits: false
  joint_2:
    has_velocity_limits: false
    has_acceleration_limits: false
  joint_3:
    has_velocity_limits: false
    has_acceleration_limits: false
  joint_4:
    has_velocity_limits: false
    has_acceleration_limits: false
  joint_5:
    has_velocity_limits: false
    has_acceleration_limits: false
