default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  waist_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  shoulder_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  forearm_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  wrist_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  palm_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  gripper_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  left_finger_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  left_fingertip_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  palm_left_finger_base_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  right_finger_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  right_fingertip_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
