# Ref: https://moveit.picknik.ai/main/doc/examples/kinematics_configuration/kinematics_configuration_tutorial.html
arthrobot_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 3
  position_only_ik: false # Only works for KDL Kinematics Plugin
  