moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arthrobot_controller

  arthrobot_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - waist_joint
      - shoulder_joint
      - forearm_joint
      - wrist_joint
      - palm_joint
      
