trajectory_execution:
  allowed_execution_duration_scaling: 1.3
  allowed_goal_duration_margin: 0.6
  allowed_start_tolerance: 0.02


moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arthrobot_controller

  arthrobot_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - waist_joint
      - shoulder_joint
      - forearm_joint
      - wrist_joint
      - palm_joint
  
  arthrobot_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_joint
      - palm_left_finger_base_joint
