arthrobot_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.02
  kinematics_solver_attempts: 5
  position_only_ik: True # Only works for KDL Kinematics Plugin