arthrobot_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.02
  kinematics_solver_timeout: 0.025
  kinematics_solver_attempts: 5
  position_only_ik: false # Only works for KDL Kinematics Plugin
  