controller_manager:
  ros__parameters:
    update_rate: 50 # command and state interface reading frequency in Hz
    use_sim_time: false

    arthrobot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arthrobot_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arthrobot_servo_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:  # publishes the current state of each joint to a topic
      type: joint_state_broadcaster/JointStateBroadcaster


# Configure the parameters of the above three controllers that will be loaded by the controller manager
arthrobot_controller:
  ros__parameters:
    joints:
      - waist_joint
      - shoulder_joint
      - forearm_joint
      - wrist_joint
      - palm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_integration_in_goal_trajectories: true
    open_loop_control: false

arthrobot_gripper_controller:
  ros__parameters:
    joints:
      - gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_integration_in_goal_trajectories: true
    open_loop_control: false


arthrobot_servo_controller:
  ros__parameters:
    joints:
      - waist_joint
      - shoulder_joint
      - forearm_joint
      - wrist_joint
      - palm_joint
